### ISSUE TITLE
Error FIREAC: Deferring connection..

### ISSUE THREAD

**Issue by Savozz** [AmirrezaJaberi/FIREAC#106] opened 2024-04-04 04:06 UTC
So i setupped FIREAC to my server and when trying to join my server its showing this: 
![image](https://github.com/AmirrezaJaberi/FIREAC/assets/86126155/c7ba79e5-dadb-4c76-85b7-b9caa3799322)
i have added the database and everything may someone help me?

**Comment by johnkouk007** [comment] 2024-05-13 12:50
me too

**Comment by HSN-ALJ** [comment] 2024-05-14 16:56
me too 🤦‍♂️

**Comment by HSN-ALJ** [comment] 2024-05-15 06:53
I've managed to solve this, The issue is occuring because of the missing DB Table

to solve this create the fireac_banlist table using the query I've written and tested.


CREATE TABLE fireac_banlist (
    STEAM VARCHAR(255),
    DISCORD VARCHAR(255),
    LICENSE VARCHAR(255),
    LIVE VARCHAR(255),
    XBL VARCHAR(255),
    IP VARCHAR(255),
    TOKENS VARCHAR(255),
    BANID INT,
    REASON TEXT
);

**Comment by HSN-ALJ** [comment] 2024-05-15 08:17
again after the last test, the data are not inserted to the tables I've created, and I have no problem for the time being but the main concern is about the administration menu, not working at all and seems like this script has alot of issues !! 

![image](https://github.com/AmirrezaJaberi/FIREAC/assets/4463265/fa64465f-4b3b-4adb-bd86-11ff7bf30ce5)

**Comment by sleepingezy** [comment] 2024-06-19 09:17
How did you add yourself to become admin. Tried putting it manually in sql but I cant seem to access admin menu

**Comment by jakemm1** [comment] 2024-07-13 09:23
> How did you add yourself to become admin. Tried putting it manually in sql but I cant seem to access admin menu

me to did u figured it out?

**Comment by AmirrezaJaberi** [comment] 2024-08-29 16:11
This bugs fixed in new version

**Closed by AmirrezaJaberi** 2024-08-29 16:11 UTC
Labels: bug
